// Plain string allowlists for the preload bridge. The preload must stay tiny and
// must not bundle zod, so it cannot import ./contract directly.
// `contract.test.ts` fails if these drift from the contract.

export const INVOKE_CHANNELS = [
  'app.ping',
  'app.info',
  'settings.get',
  'settings.patch',
  'ble.prepare',
  'ble.choose',
  'ble.requestAutoConnect',
  'journal.begin',
  'journal.append',
  'journal.close',
  'journal.remove',
  'journal.pending',
  'journal.read',
  'files.saveFit',
  'files.exportDir',
  'files.chooseExportDir',
  'files.reveal',
  'files.saveAs',
  'files.openUrl',
  'support.reportBug',
  'files.exportZwift',
  'music.status',
  'music.command',
  'files.listFits',
  'files.readFit',
  'power.keepAwake',
  'strava.status',
  'strava.setApp',
  'strava.connect',
  'strava.disconnect',
  'intervals.status',
  'intervals.configure',
  'intervals.clear',
  'uploads.enqueue',
  'uploads.list',
  'uploads.retry',
  'ai.status',
  'ai.configure',
  'ai.models',
  'ai.complete',
  'ai.structured',
  'ai.stream.start',
  'ai.stream.cancel',
  'minihud.toggle',
  'minihud.setClickThrough',
  'ride.command',
  'remote.start',
  'remote.stop',
  'remote.status',
  'remote.kick',
] as const

export const SEND_CHANNELS = ['live.publish'] as const

export const EVENT_CHANNELS = ['app.log', 'settings.changed', 'ble.chooser', 'ble.chosen', 'power.suspend', 'uploads.changed', 'ai.stream.delta', 'ai.stream.end', 'live.broadcast', 'ride.command'] as const
