// Banned-topic guardrails for everything a coach may say: canned lines, lines
// from user-authored packs, and (later) AI output. Coaches roast effort,
// choices and excuses, never who someone is. The lists are curated regexes and
// deliberately conservative: a false positive only costs one line, while a
// miss is spoken aloud to someone mid-interval.
//
// Matching runs on normalized text: lowercase, accents stripped, curly
// apostrophes folded, and leetspeak between letters undone ("f4t" → "fat").

export type GuardrailCategory =
  | 'self-harm'
  | 'violence'
  | 'ethnicity'
  | 'religion'
  | 'sexuality'
  | 'gender'
  | 'health'
  | 'body'
  | 'politics'

export interface GuardrailRule {
  category: GuardrailCategory
  /** Matches normalized text (see normalizeForMatching). */
  pattern: RegExp
}

// Each entry is a regex fragment, wrapped in \b(?: … )\b when compiled.
const TERMS: Record<GuardrailCategory, readonly string[]> = {
  'self-harm': [
    'suicid(?:e|es|al)',
    'kill (?:yourself|yourselves|urself|myself)',
    'kys',
    'unalive',
    'end (?:it all|your life|your own life|my life)',
    'take your (?:own )?life',
    'self[- ]?harm(?:ing)?',
    'cut(?:ting)? (?:yourself|myself)',
    'slit (?:your |my )?wrists?',
    'hang (?:yourself|myself)',
    'jump off (?:a|the) (?:bridge|cliff|building|roof)',
    'overdos(?:e|ed|es|ing)',
    'anorexi(?:a|c)',
    'bulimi(?:a|c)',
    'eating disorders?',
    'starv(?:e|ing) yourself',
    'purg(?:e|es|ing)',
    'go die',
    'just die',
    'die already',
    'hope you die',
    'should (?:just )?die',
    'drop dead',
    'wish (?:you|i) (?:were|was) dead',
    'better off dead',
    'kill me now',
    '(?:want|wanna|wants) to die',
    'death wish',
    'cry for help',
  ],
  violence: [
    'wars?',
    'warfare',
    'wartime',
    'war ?zones?',
    'battlefields?',
    'genocid(?:e|al)',
    'massacr(?:e|es|ed)',
    'slaughter(?:s|ed|ing)?',
    'exterminat\\w*',
    'ethnic cleansing',
    'holocaust',
    'pogroms?',
    'terror(?:ism|ist|ists)',
    'terror attacks?',
    'suicide bomb\\w*',
    'bombings?',
    'bombed',
    'bombers?',
    'car bombs?',
    'nukes?',
    'nuked',
    'nuclear (?:war|wars|strike|strikes|attack|attacks|holocaust)',
    'air ?strikes?',
    'drone strikes?',
    'missile strikes?',
    'missiles?',
    'rocket fire',
    'artillery',
    'shelling',
    'invasions?',
    'invad(?:e|ed|es|ing)',
    'hostages?',
    'kidnap\\w*',
    'casualt(?:y|ies)',
    'civilians?',
    'war crimes?',
    'behead\\w*',
    'lynch\\w*',
    'mass shootings?',
    'school shootings?',
    'shooters?',
    'gunm[ae]n',
    'guns?',
    'gunfire',
    'rifles?',
    'pistols?',
    'firearms?',
    'shotguns?',
    'ak-?47s?',
    'ar-?15s?',
    'grenades?',
    'landmines?',
    'machine guns?',
    'snipers?',
    'stab(?:bed|bing|bings)',
    'stab (?:him|her|them|you|people)',
    'murder\\w*',
    'homicid\\w*',
    'assassinat\\w*',
    'concentration camps?',
    'gas chambers?',
    'gulags?',
    'death camps?',
    'death squads?',
    'firing squads?',
    'militias?',
    'insurgen\\w*',
    'jihad\\w*',
    'martyr\\w*',
    'shoot (?:him|her|them|you|people|up|everyone|everybody)',
    'kill(?:ing)? (?:them|em|everyone|everybody|people|all)',
    'execute (?:him|her|them|people|everyone)',
    'hang (?:him|her|them)',
    'rap(?:e|ed|es|ist|ists|ing)',
    'violen(?:ce|t)',
    'riot(?:s|ing|ers)?',
    'abus(?:e|ed|er|ers|ive)',
    'enslav\\w*',
    'slaves?',
    'slavery',
  ],
  ethnicity: [
    'racial(?:ly)?',
    'racis(?:t|ts|m)',
    'race wars?',
    'ethnic(?:ity|ities|ally)?',
    'skin colou?rs?',
    'colou?red (?:people|folks|persons?|guys?)',
    '(?:black|white|brown|yellow|red) (?:people|guys?|m[ae]n|wom[ae]n|folks|persons?|boys?|girls?|trash)',
    'asians?',
    'oriental',
    'hispanics?',
    'latin(?:o|a|os|as|x)',
    'africans?',
    'caucasians?',
    'arabs?',
    'arabic',
    'aborigin\\w*',
    'indigenous',
    'native americans?',
    'redskins?',
    'eskimos?',
    'gyps(?:y|ies)',
    'gypped',
    'negro(?:es)?',
    'n[i1!]gg\\w*',
    'ch[i1]nks?',
    'sp[i1]cs?',
    'k[i1]kes?',
    'w[e3]tbacks?',
    'g[o0]{2}ks?',
    'towelheads?',
    'ragheads?',
    'camel jockeys?',
    'beaners?',
    'wops?',
    'dagos?',
    'krauts?',
    'japs?',
    'pakis?',
    'gringos?',
    'honk(?:y|ie|ies)',
    'rednecks?',
    'hillbill(?:y|ies)',
    'ghettos?',
    'thugs?',
    'immigrants?',
    'immigration',
    'migrants?',
    'refugees?',
    'illegal aliens?',
    'illegals',
    'foreigners?',
    'third world',
    'go back to (?:your|where)',
    'anchor bab(?:y|ies)',
    'nationalit(?:y|ies)',
    'nationalis(?:m|t|ts)',
    // demonyms: jokes about where someone is from are off the table
    'americans?',
    'yankees?',
    'british',
    'brits?',
    'english(?:m[ae]n|wom[ae]n)?',
    'irish(?:m[ae]n)?',
    'scottish',
    'scots?',
    'welsh',
    'french(?:m[ae]n|ie|ies)?',
    'germans?',
    'italians?',
    'spanish',
    'spaniards?',
    'portuguese',
    'dutch(?:m[ae]n)?',
    'belgians?',
    'swiss',
    'austrians?',
    'swedish',
    'swedes?',
    'norwegians?',
    'danish',
    'danes?',
    'finnish',
    'finns?',
    'poles',
    'polacks?',
    'russians?',
    'ukrainians?',
    'greeks?',
    'turkish',
    'turks?',
    'israelis?',
    'palestinians?',
    'iranians?',
    'persians?',
    'iraqis?',
    'syrians?',
    'lebanese',
    'egyptians?',
    'saudis?',
    'emiratis?',
    'afghans?',
    'afghanis?',
    'pakistanis?',
    'indians?',
    'bangladeshis?',
    'chinese',
    'japanese',
    'koreans?',
    'vietnamese',
    'thai',
    'filipin(?:o|a|os|as)',
    'indonesians?',
    'malaysians?',
    'australians?',
    'aussies?',
    'canadians?',
    'mexicans?',
    'brazilians?',
    'argentin(?:e|es|ian|ians)',
    'colombians?',
    'chileans?',
    'peruvians?',
    'venezuelans?',
    'cubans?',
    'nigerians?',
    'kenyans?',
    'ethiopians?',
    'somalis?',
    'moroccans?',
    'algerians?',
    'slavs?',
    'slavic',
    'balkans?',
    'romanians?',
    'bulgarians?',
    'serbs?',
    'serbians?',
    'croats?',
    'croatians?',
    'czechs?',
    'slovaks?',
    'hungarians?',
    'europeans?',
  ],
  religion: [
    'gods?',
    'goddess(?:es)?',
    'goddamn(?:ed|it)?',
    'godless',
    'jesus',
    'christ',
    'christians?',
    'christianity',
    'catholic(?:s|ism)?',
    'protestants?',
    'evangelicals?',
    'mormons?',
    'amish',
    'allah',
    'muhammad',
    'mohammed',
    'prophets?',
    'islam(?:ic|ist|ists)?',
    'muslims?',
    'moslems?',
    'jews?',
    'jewish',
    'judaism',
    'hebrews?',
    'rabbis?',
    'kosher',
    'halal',
    'synagogues?',
    'mosques?',
    'church(?:es)?',
    'cathedrals?',
    'chapels?',
    'temples?',
    'bibles?',
    'biblical',
    "qur'?an",
    'koran',
    'torah',
    'talmud',
    'scriptures?',
    'gospels?',
    'psalms?',
    'sermons?',
    'pray(?:s|ed|er|ers|ing)?',
    'bless(?:ed|es|ing|ings)?',
    'holy',
    'holier',
    'sacred',
    'divine',
    'divinity',
    'sins?',
    'sinners?',
    'sinful',
    'satan(?:ic)?',
    'devils?',
    'demons?',
    'demonic',
    'heaven(?:s|ly)?',
    'angels?',
    'angelic',
    'saints?',
    'popes?',
    'priests?',
    'pastors?',
    'preachers?',
    'imams?',
    'monks?',
    'nuns?',
    'buddha',
    'buddhis(?:m|t|ts)',
    'hindus?',
    'hinduism',
    'sikhs?',
    'sikhism',
    'atheis(?:m|t|ts)',
    'karma',
    'nirvana',
    'reincarnat\\w*',
    'chakras?',
    'namaste',
    'om+',
    'amen',
    'hallelujah',
    'messiah',
    'crucif\\w*',
    'resurrect\\w*',
    'baptis\\w*',
    'crusad(?:e|es|er|ers)',
    'infidels?',
    'heretics?',
    'heresy',
    'blasphem\\w*',
    'sabbath',
    'shabbat',
    'ramadan',
    'hanukk?ah',
    'chanukk?ah',
    'passover',
    'easter',
    'christmas',
    'xmas',
    'diwali',
    'yom kippur',
    'zion(?:ism|ist|ists)?',
    'antisemit\\w*',
    'chosen people',
    'promised land',
    'spiritual(?:ity|ly)?',
    'afterlife',
    'hellfire',
    'damnation',
    'worship\\w*',
    'altars?',
    'cults?',
    'religio(?:n|ns|us)',
    'faiths',
  ],
  sexuality: [
    'sex',
    'sexy',
    'sexier',
    'sexiest',
    'sexual(?:ly|ity)?',
    'sexting',
    'porn\\w*',
    'nudes?',
    'nudity',
    'naked',
    'horny',
    'orgasm\\w*',
    'boners?',
    'erections?',
    'arous(?:ed|al|ing)',
    'kinky',
    'fetish\\w*',
    'foreplay',
    'strippers?',
    'strip clubs?',
    'hookers?',
    'prostitut\\w*',
    'escorts?',
    'brothels?',
    'humping',
    'penis(?:es)?',
    'vaginas?',
    'genitals?',
    'genitalia',
    'boobs?',
    'boobies',
    'tits?',
    'titties',
    'nipples?',
    'balls',
    'testicles?',
    'scrotum',
    'dicks?',
    'cocks?',
    'puss(?:y|ies)',
    'condoms?',
    'viagra',
    'virgins?',
    'virginity',
    'sluts?',
    'slutty',
    'whores?',
    'thots?',
    'milfs?',
    'onlyfans',
    'gay',
    'gays',
    'lesbians?',
    'bisexual\\w*',
    'homosexual\\w*',
    'heterosexual\\w*',
    'queers?',
    'homos?',
    'fag(?:s|got|gots|gy)?',
    'dykes?',
    'trann(?:y|ies)',
    'transgender\\w*',
    'transsexual\\w*',
    'trans (?:m[ae]n|wom[ae]n|people|persons?|kids?)',
    'non-?binary',
    'lgbt\\w*',
    'drag queens?',
    'twinks?',
    'femboys?',
    'no homo',
    '(?:came|come|comes|coming) out as',
    'in the closet',
    'pronouns?',
  ],
  gender: [
    'like (?:a )?(?:little )?girls?',
    'like an? (?:old )?(?:lady|woman|women)',
    'like (?:my|your|his|her) (?:grandma|granny|grandmother|grandpa|grandfather|mom|mum|mother|sister|wife|girlfriend)',
    'man up',
    'grow a pair',
    'sissy',
    'sissies',
    'pansy',
    'pansies',
    'girly',
    'girlie',
    'be a man',
    'real m[ae]n',
    'act like a man',
    'pms',
    'pmsing',
    'on (?:her|your|the) period',
    'hormonal',
    'bitch(?:es|y|ing)?',
    'wuss(?:y|ies)?',
    "(?:women|girls) (?:can'?t|shouldn'?t|don'?t)",
    'make me a sandwich',
  ],
  health: [
    'cancer',
    'tumou?rs?',
    'diabet(?:es|ic)',
    'asthma(?:tic)?',
    'epilep(?:sy|tic)',
    'seizures?',
    'heart attacks?',
    'cardiac arrest',
    'heart (?:disease|condition|failure)',
    'arrhythmia',
    'a-?fib',
    '(?:had|having|have|has|gonna have|going to have|give me|give you) a stroke',
    'stroke victims?',
    'copd',
    'dementia',
    "alzheimer'?s",
    "parkinson'?s",
    'hiv',
    'covid(?:-19)?',
    'coronavirus',
    'pandemic',
    'flu',
    'influenza',
    'pneumonia',
    'tuberculosis',
    'leuka?emia',
    'chemo(?:therapy)?',
    'diseases?',
    'diseased',
    'illness(?:es)?',
    'ill',
    'sick(?:ness|ly|o|os)?',
    'infections?',
    'virus(?:es)?',
    'injur(?:y|ies|ed|e|es|ing)',
    'broken (?:bones?|legs?|arms?|wrists?|collarbones?|hips?|necks?|backs?)',
    'fractur(?:e|ed|es)',
    'concussions?',
    'torn (?:acl|mcl|ligaments?|muscles?|meniscus)',
    'acl',
    'sprain(?:s|ed)?',
    'surger(?:y|ies)',
    'hospital(?:s|ised|ized)?',
    'ambulances?',
    'paramedics?',
    'emergency room',
    'icu',
    'road rash',
    'stitches',
    'wheelchairs?',
    'crutches',
    'hurt(?:ing)? (?:yourself|yourselves|himself|herself|themselves)',
    'disabled',
    'disabilit(?:y|ies)',
    'handicap(?:s|ped)?',
    'crippl(?:e|ed|es|ing)',
    'lame',
    'paraplegic',
    'quadriplegic',
    'amputees?',
    'deaf',
    'dumb',
    'retard(?:s|ed)?',
    'tards?',
    'spaz(?:zing|zy)?',
    'spastic',
    'mongoloid',
    "down'?s syndrome",
    'autis(?:m|tic)',
    'aspie',
    'adhd',
    'ocd',
    'bipolar',
    'schizo(?:phrenic|phrenia)?',
    'psycho(?:s|path|paths|tic|sis)?',
    'lunatics?',
    'mental(?:ly)? (?:illness|ill|case|disorder|patient|hospital)',
    'special needs',
    'brain[- ]damage(?:d)?',
    'medication',
    'meds',
    'pills',
    'prescription',
    'inhaler',
    'defibrillator',
    'cpr',
    'vomit(?:s|ing|ed)?',
    'puk(?:e|ed|es|ing)',
    'throw(?:ing)? up',
    'threw up',
    'barf(?:s|ed|ing)?',
    'pass(?:ed|ing)? out',
    'faint(?:ed|ing)?',
    'black(?:ed|ing)? out',
  ],
  body: [
    'fat',
    'fats',
    'fatty',
    'fatties',
    'fatso',
    'fatter',
    'fattest',
    'fatass',
    'lardass',
    'lard',
    'blubber(?:y)?',
    'chubby',
    'chubbier',
    'chunky',
    'pudgy',
    'podgy',
    'plump',
    'porky',
    'flab(?:by)?',
    'obes(?:e|ity)',
    'overweight',
    'underweight',
    'skinny',
    'scrawny',
    'bony',
    'beanpole',
    'ugl(?:y|ier|iest)',
    'hideous',
    'unattractive',
    'homely',
    'bell(?:y|ies)',
    'potbell(?:y|ied)',
    'paunch',
    'love handles',
    'muffin tops?',
    'double chins?',
    'man boobs',
    'moobs',
    'dad bods?',
    'thunder thighs',
    'cankles',
    'thick thighs',
    'big (?:butt|ass|bum)',
    'fat (?:ass|butt|bum)',
    'wide load',
    'junk in the trunk',
    'cellulite',
    'stretch marks',
    'saggy',
    'jiggl(?:e|y|ing)',
    '(?:beer|pot|your|his|her|big|that) gut',
    '(?:lose|losing|lost|shed|shedding|drop|dropping|gain|gaining|gained|put on) (?:some |a few |a little |the |that |those |your |more )?(?:weight|pounds|lbs|kilos|belly|flab|fat)',
    '(?:your|his|her|their|my) (?:weight|waistline|waist|bmi|body fat|figure|physique)',
    'bmi',
    'body mass',
    'body fat',
    'body shapes?',
    'body types?',
    'beach body',
    'bikini body',
    'summer body',
    'diet(?:s|ing|er|ers)?',
    'calorie deficit',
    'burn(?:ing)? (?:it )?off',
    'weigh(?:s|ing)? (?:a ton|too much|more than)',
    'bald(?:ing)?',
    'hairline',
    'wrinkl(?:y|es|ed)',
    'zits?',
    'pimples?',
    'acne',
    'big nose',
    'buck teeth',
    'your face',
    'ugly mug',
    'you look like',
    'you smell',
    'you stink',
    'smelly',
    'stinky',
    'midgets?',
    'dwarfs?',
    'manlet',
    'shorty',
    'pregnan(?:t|cy)',
  ],
  politics: [
    'politic(?:s|al|ally|ian|ians)',
    'democrats?',
    'democratic party',
    'republicans?',
    'gop',
    'liberals',
    'libtards?',
    'leftists?',
    'lefty',
    'lefties',
    'left-wing',
    'right-wing',
    'far-left',
    'far-right',
    'alt-right',
    'conservatives',
    'tor(?:y|ies)',
    'labou?r party',
    'green party',
    'socialis(?:m|t|ts)',
    'communis(?:m|t|ts)',
    'commies?',
    'fascis(?:m|t|ts)',
    'nazis?',
    'nazism',
    'neo-?nazis?',
    'marxis(?:m|t|ts)',
    'maga',
    'woke(?! up)',
    'wokeness',
    'antifa',
    'snowflakes?',
    'elections?',
    'electoral',
    'electioneering',
    'vot(?:e|es|ed|er|ers|ing)',
    'ballots?',
    'referend(?:um|ums|a)',
    'brexit',
    'impeach\\w*',
    'senators?',
    'congress(?:m[ae]n|wom[ae]n|person)',
    'parliamentar\\w*',
    'presidents?',
    'presidential',
    'prime ministers?',
    'chancellors?',
    'dictators?',
    'dictatorship',
    'supreme leader',
    'coup',
    'propaganda',
    'abortion',
    'pro-life',
    'pro-choice',
    'gun control',
    'border wall',
    'deport\\w*',
    'white house',
    'downing street',
    'kremlin',
    // real politicians and movements
    'trump\\w*',
    'biden',
    'obama',
    'clinton',
    'pelosi',
    'desantis',
    'kamala',
    'putin',
    'zelensk\\w*',
    'xi jinping',
    'kim jong[- ]?\\w*',
    'netanyahu',
    'erdogan',
    'modi',
    'macron',
    'trudeau',
    'starmer',
    'sunak',
    'thatcher',
    'boris johnson',
    'hitler',
    'stalin',
    'mussolini',
    'mao',
    'khamenei',
    'sinwar',
    'bin laden',
    'gaddafi',
    'saddam',
    'castro',
    'likud',
    'knesset',
    'hamas',
    'hezbollah',
    'isis',
    'taliban',
    'al[- ]qaeda',
    // geopolitics
    'israel',
    'palestine',
    'gaza',
    'west bank',
    'jerusalem',
    'iran',
    'iraq',
    'syria',
    'lebanon',
    'afghanistan',
    'ukraine',
    'russia',
    'crimea',
    'donbas',
    'taiwan',
    'north korea',
    'tibet',
    'kashmir',
    'yemen',
    'sudan',
    'darfur',
    'myanmar',
    'rohingya',
    'uyghurs?',
    'kurd(?:s|ish|istan)?',
  ],
}

/** Most severe first: the first category that matches is reported. */
const CATEGORY_ORDER: readonly GuardrailCategory[] = [
  'self-harm',
  'violence',
  'ethnicity',
  'religion',
  'sexuality',
  'gender',
  'health',
  'body',
  'politics',
]

function compile(terms: readonly string[]): RegExp {
  return new RegExp(`\\b(?:${terms.join('|')})\\b`, 'i')
}

export const GUARDRAILS: readonly GuardrailRule[] = CATEGORY_ORDER.map((category) => ({
  category,
  pattern: compile(TERMS[category]),
}))

const LEET: Record<string, string> = { '0': 'o', '1': 'i', '3': 'e', '4': 'a', '5': 's', '7': 't', '@': 'a', '$': 's', '!': 'i' }

/** Lowercase, strip accents, fold apostrophes, undo leetspeak between letters, squash whitespace. */
export function normalizeForMatching(text: string): string {
  return text
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[‘’ʼ`´]/g, "'")
    .replace(/(?<=[a-z])[013457@$!](?=[a-z])/g, (c) => LEET[c] ?? c)
    .replace(/\s+/g, ' ')
}

export interface GuardrailMatch {
  category: GuardrailCategory
  /** The text that matched, for error messages. */
  match: string
}

export function guardrailMatch(text: string): GuardrailMatch | null {
  const norm = normalizeForMatching(text)
  for (const rule of GUARDRAILS) {
    const m = rule.pattern.exec(norm)
    if (m) return { category: rule.category, match: m[0] }
  }
  return null
}

/** The banned category a text touches, or null when it is clean. Use it on AI output too. */
export function violatesGuardrails(text: string): GuardrailCategory | null {
  return guardrailMatch(text)?.category ?? null
}

// Profanity is a user setting, not a guardrail. Clean drops both kinds, Mild
// allows the mild list only, Unhinged allows everything.
const MILD_PROFANITY = compile([
  'damn(?:s|ed|it)?',
  'dammit',
  'hell',
  'crap(?:s|py|pier)?',
  'bloody',
  'arse',
  'ass',
  'asses',
  'badass',
  'half-ass(?:ed)?',
  'kick-?ass',
  'smart-?ass',
  'jackass',
  'dumbass',
  'piss(?:es|ed|ing)?',
  'piss-poor',
  'freaking',
  "frickin(?:g|')?",
  "friggin(?:g|')?",
  'bugger',
  'sod (?:off|it)',
  'bollocks',
  'screw (?:it|this|that|you)',
])

const STRONG_PROFANITY_WORDS = compile([
  'f+u+c+k\\w*',
  'fck\\w*',
  'fuk\\w*',
  'motherf\\w*',
  'mofo',
  'sh[i1]t\\w*',
  'bullsh[i1]t\\w*',
  'cunts?',
  'twats?',
  'wank\\w*',
  'bitch\\w*',
  'bastards?',
  'assholes?',
  'arseholes?',
  'dick(?:s|head|heads)?',
  'cocks?',
  'cocksuck\\w*',
  'puss(?:y|ies)',
  'pricks?',
  'sluts?',
  'whores?',
  'goddamn\\w*',
  'son of a bitch',
  'wtf',
  'stfu',
  'omfg',
  'douche(?:bag|bags)?',
  'asshats?',
  'numbnuts',
  'dickwads?',
  'bellends?',
  'knob(?:head|heads)?',
  'tossers?',
  'pillocks?',
])
/** Censored forms ("f***", "sh*t") count as strong: the intent is the same. */
const CENSORED_PROFANITY = /\b(?:f|sh)[*#@]+/i

export type ProfanityLevel = 'mild' | 'strong'

export function detectProfanity(text: string): ProfanityLevel | null {
  const norm = normalizeForMatching(text)
  if (STRONG_PROFANITY_WORDS.test(norm) || CENSORED_PROFANITY.test(norm)) return 'strong'
  if (MILD_PROFANITY.test(norm)) return 'mild'
  return null
}

/** Does the text's language fit the rider's setting (Clean, Mild or Unhinged). */
export function languageAllowed(text: string, setting: 'clean' | 'mild' | 'unhinged'): boolean {
  if (setting === 'unhinged') return true
  const found = detectProfanity(text)
  return found === null || (setting === 'mild' && found === 'mild')
}
